image: nixos/nix:latest
variables:
  NIX_PATH: 'nixpkgs=channel:nixos-unstable'
  NIX_CONFIG: 'experimental-features = nix-command flakes'

stages:
  - check

check:
  # Não rodar pipeline pro push na branch se tiver um MR aberto nela (pipeline duplicado)
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  stage: check
  script:
    - nix flake check
