image: nixos/nix:latest
variables:
  NIX_PATH: 'nixpkgs=channel:nixos-unstable'
  NIX_CONFIG: 'experimental-features = nix-command flakes'

stages:
  - check
  - deploy

check:
  # Não rodar pipeline pro push na branch se tiver um MR aberto nela (pipeline duplicado)
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH
  stage: check
  script:
    - nix flake check

deploy:
  # Apenas rodar na main
  rules:
    - if: $CI_COMMIT_REF_NAME == 'main'
  stage: deploy
  before_script:
    - nix profile install nixpkgs#{openssh,cachix}
    - cachix authtoken $CACHIX_KEY
    - cachix use gelos-icmc
    - cat $KNOWN_HOSTS >> ~/.ssh/known_hosts
  script:
    - cachix watch-exec gelos-icmc -- nix run '.#deploy-rs' -- --ssh-user="cicd" --ssh-opts="-p 2112 -i $DEPLOY_KEY"
