image: nixos/nix:latest
variables:
  NIX_PATH: 'nixpkgs=channel:nixos-unstable'
  NIX_CONFIG: 'experimental-features = nix-command flakes'

stages:
  - build
  - deploy

.rules: &rules
  - if: $CI_COMMIT_REF_NAME == 'main'
    variables:
      BASEURL: ''
      ENV_NAME: 'production'
      ENV_URL: 'gelos.club'
  - if: $CI_COMMIT_REF_NAME != 'main'
    variables:
      BASEURL: '$CI_COMMIT_REF_NAME'
      ENV_NAME: 'review/$CI_COMMIT_REF_NAME'
      ENV_URL: 'review.gelos.club/$CI_COMMIT_REF_NAME'

build:
  stage: build
  rules:
    - *rules
  before_script:
    - nix-env -iA nixpkgs.git
  script:
    - 'echo "baseurl: $BASEURL" >> _config.yml'
    - nix build
    - tar -C result/public -cvz . > site.tar.gz
  artifacts:
    name: '$ENV_NAME'
    paths:
      - site.tar.gz
    expire_in: 5 days

deploy:
  stage: deploy
  rules:
    - *rules
  environment:
    name: '$ENV_NAME'
    url: 'https://$ENV_URL'
  before_script:
    - nix-channel --add https://nixos.org/channels/nixos-unstable nixos
    - nix-channel --update
    - nix-env -iA nixos.hut
  script:
    - hut --config $SOURCEHUT_OAUTH pages publish -d $ENV_URL --not-found "/404" site.tar.gz
