name: "GELOS"
description: "Grupo de Extensão Livre & Open Source - ICMC USP"
url: "https://geos.misterio.me"

sass:
  style: compact

# Permalink dos posts
permalink: /:year/:month/:day/:title:output_ext

# Incluir páginas
collections:
  pages:
    output: true
    permalink: /:path

# Definir variáveis para páginas
defaults:
  # Fazer páginas usarem o layout default
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  # Fazer posts usarem o layout post
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

  # Posts dentro da pasta noticias terão a categoria notícias
  -
    scope:
      path: "_posts/noticias"
    values:
      category: "noticias"
  # Posts dentro da pasta relatorios terão a categoria relatorios
  -
    scope:
      path: "_posts/relatorios"
    values:
      category: "relatorios"
  # Posts dentro da pasta documentos terão a categoria documentos
  -
    scope:
      path: "_posts/documentos"
    values:
      category: "documentos"
