name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    environment:
      name: galapagos
      url: https://gelos.club
    uses: gelos-icmc/actions/.github/workflows/deploy.yml@main
    secrets: inherit
